#!/usr/bin/env python3
"""
OpenJury SDK Demo

This script demonstrates how to use the OpenJury Python SDK to evaluate multiple responses
using a configurable jury of LLM jurors.

Usage:
    python examples/basic_jury_run.py

Requirements:
    - Set OPENROUTER_API_KEY environment variable
    - Install dependencies: pip install openjury
"""

import logging
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from openjury import JuryConfig, OpenJury, ResponseCandidate

logging.basicConfig(level=logging.INFO, format="%(levelname)s - %(message)s")
logger = logging.getLogger("basic_jury_run")


def display_verdict_summary(verdict):
    logger.info("\n" + "=" * 60)
    logger.info("Jury Verdict Summary")
    logger.info("=" * 30)

    logger.info(f"Winner: {verdict.final_verdict.winner}")
    logger.info(f"Confidence: {verdict.final_verdict.confidence:.2%}")

    logger.info("\n" + "-" * 60)
    logger.info("Individual Juror Verdicts")
    logger.info("-" * 60)

    for juror_verdict in verdict.juror_verdicts:
        best_response = None
        best_score = 0
        for evaluation in juror_verdict.evaluations:
            if evaluation.total_score > best_score:
                best_score = evaluation.total_score
                best_response = evaluation.response_id

        logger.info(f"Juror: {juror_verdict.juror_name}")
        logger.info(f"  Weight: {juror_verdict.juror_weight}")
        logger.info(f"  Top Choice: {best_response or 'N/A'}")
        logger.info(f"  Score: {best_score:.1f}" if best_response else "  Score: N/A")


def main():
    api_key = os.getenv("OPENROUTER_API_KEY")
    assert api_key, "OPENROUTER_API_KEY environment variable is not set"

    config_path = f"{Path(__file__).parent}/config.json"

    try:
        jury_config = JuryConfig.from_json_file(config_path)
    except Exception as e:
        logger.error(f"❌ Failed to load configuration: {e}")
        return

    prompt = "I've been feeling tired and dizzy lately. I'm a 42-year-old woman with no major medical history, but I recently started a low-carb diet. What could be causing this, and should I see a doctor?"

    # In production, these responses would be generated by different LLMs.
    responses = [
        ResponseCandidate(
            content="""
            Your symptoms may be related to the dietary changes you've made. Starting a low-carb diet, especially a ketogenic one, can sometimes lead to what's known as the "keto flu," which includes fatigue, dizziness, and irritability. These symptoms typically occur as your body adjusts to burning fat instead of carbohydrates.
            However, dizziness and fatigue can also stem from dehydration, low blood pressure, low blood sugar, or electrolyte imbalances — all of which can be affected by dietary changes. In some cases, underlying conditions like anemia or thyroid issues can present similarly.
            It's advisable to stay hydrated, ensure adequate salt and electrolyte intake, and monitor your symptoms. If they persist for more than a few days, worsen, or interfere with daily activities, you should definitely consult a healthcare provider to rule out other causes
            """,
            model_name="gpt-4o",
        ),
        ResponseCandidate(
            content="""
            Thank you for providing that context. Fatigue and dizziness are common when starting a low-carb or ketogenic diet. As your body transitions to a different energy source (from carbs to fats), it can temporarily react with symptoms like the ones you're experiencing.
            These effects can also be linked to reduced blood sugar levels, electrolyte shifts, or dehydration, especially if you're not consuming enough fluids or salt. It's important to rest, stay hydrated, and ensure you're eating nutrient-dense foods.
            If symptoms continue beyond a week, or if they become severe or alarming, I strongly encourage you to speak with a doctor. They can check for other causes like anemia, vitamin deficiencies, or hormonal imbalances. Always trust your body and seek care when something feels off.
            """,
            model_name="claude-3.5-sonnet",
        ),
        ResponseCandidate(
            content="""
            Feeling tired and dizzy could be due to changes from your new diet. Low-carb plans can affect your blood sugar and energy levels, especially early on. Make sure you're staying hydrated and getting enough electrolytes like sodium and potassium.
            If the symptoms don't go away soon or get worse, it's a good idea to talk to a doctor just to be safe.
            """,
            model_name="qwen-2.5-72b",
        ),
    ]

    logger.info(
        f"Evaluating {len(responses)} responses with {len(jury_config.jurors)} jurors..."
    )
    try:
        jury = OpenJury(jury_config)
        verdict = jury.evaluate(prompt=prompt, responses=responses)
        display_verdict_summary(verdict)
    except Exception as e:
        logger.error(f"Evaluation failed: {e}")
        logger.exception("Detailed error:")
    logger.info("Evaluation complete!")


if __name__ == "__main__":
    main()
