#!/usr/bin/env python3
"""Export the assertion conformance fixture.

The fixture is a specification of what OpenJury's deterministic checks mean,
expressed as {response, assertion, passed} triples generated by running
`evaluate_assertions` itself. It exists so a reimplementation in another
language can prove it agrees, and so OpenJury notices if its own semantics
drift.

Cases deliberately cover the places a naive port diverges silently: casefold
versus lowercase, code points versus UTF-16 units, `regex` matching the raw
response, and Python's `re` dialect.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict, List

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from openjury.assertions import evaluate_assertions  # noqa: E402
from openjury.config import AssertionConfig  # noqa: E402

OUTPUT = REPO_ROOT / "docs" / "assertion_conformance.json"

SCHEMA_VERSION = 1

NOTES = [
    "Generated from openjury.assertions.evaluate_assertions; do not edit by hand.",
    "Regenerate with: python scripts/export_assertion_conformance.py",
    "Case-insensitive matching uses Python str.casefold(), which is more "
    "aggressive than a plain lowercase and is locale-independent.",
    "min_length and max_length count Unicode code points (Python len()), not "
    "UTF-16 code units.",
    "regex matches the raw response, not the case-normalized one; with "
    "case_sensitive=false it applies re.IGNORECASE instead.",
    "regex patterns are Python re. Cases tagged 'python_re_only' use syntax "
    "other dialects reject; a port should skip them and treat regex as "
    "advisory rather than claim parity.",
    "Empty string values are rejected by AssertionConfig validation, so no "
    "case here carries one.",
]

# (id, description, tags, response, assertion payload)
CASES: List[tuple[str, str, List[str], str, Dict[str, Any]]] = [
    (
        "contains-hit",
        "Substring present",
        [],
        "The answer is 42.",
        {"type": "contains", "value": "answer"},
    ),
    (
        "contains-miss",
        "Substring absent",
        [],
        "The answer is 42.",
        {"type": "contains", "value": "disclaimer"},
    ),
    (
        "contains-case-sensitive-miss",
        "Case-sensitive matching does not fold case",
        [],
        "Read the Refund Policy first.",
        {"type": "contains", "value": "refund policy"},
    ),
    (
        "contains-case-insensitive-hit",
        "The same pair matches once case folding is on",
        [],
        "Read the Refund Policy first.",
        {"type": "contains", "value": "refund policy", "case_sensitive": False},
    ),
    (
        "contains-casefold-sharp-s",
        "casefold folds ß to ss; a plain lowercase does not",
        ["casefold"],
        "Die Straße ist gesperrt.",
        {"type": "contains", "value": "STRASSE", "case_sensitive": False},
    ),
    (
        "contains-casefold-ligature",
        "casefold decomposes the ﬁ ligature; a plain lowercase does not",
        ["casefold"],
        "The ﬁle is ready.",
        {"type": "contains", "value": "file", "case_sensitive": False},
    ),
    (
        "equals-casefold-final-sigma",
        "Greek final sigma folds together with sigma",
        ["casefold"],
        "ΟΔΟΣ",
        {"type": "equals", "value": "οδος", "case_sensitive": False},
    ),
    (
        "contains-casefold-turkish-dotless-i",
        "casefold is locale-independent: dotless ı does not fold with I",
        ["casefold", "locale"],
        "ırmak kenarı",
        {"type": "contains", "value": "IRMAK", "case_sensitive": False},
    ),
    (
        "contains-casefold-turkish-dotted-i",
        "casefold turns İ into i plus a combining dot, so 'istanbul' does not match",
        ["casefold", "locale"],
        "İSTANBUL",
        {"type": "contains", "value": "istanbul", "case_sensitive": False},
    ),
    (
        "not_contains-pass",
        "Forbidden phrase absent",
        [],
        "Here is a summary of the policy.",
        {"type": "not_contains", "value": "guaranteed returns"},
    ),
    (
        "not_contains-fail",
        "Forbidden phrase present",
        [],
        "This offers guaranteed returns.",
        {"type": "not_contains", "value": "guaranteed returns"},
    ),
    (
        "equals-exact",
        "Whole response equals the value",
        [],
        "APPROVED",
        {"type": "equals", "value": "APPROVED"},
    ),
    (
        "equals-trailing-whitespace",
        "equals does not trim; trailing whitespace fails",
        ["whitespace"],
        "APPROVED ",
        {"type": "equals", "value": "APPROVED"},
    ),
    (
        "not_equals-pass",
        "Whole response differs from the value",
        [],
        "APPROVED WITH NOTES",
        {"type": "not_equals", "value": "APPROVED"},
    ),
    (
        "not_equals-fail",
        "Whole response equals the value",
        [],
        "APPROVED",
        {"type": "not_equals", "value": "APPROVED"},
    ),
    (
        "starts_with-pass",
        "Response opens with the value",
        [],
        "Dear customer, your order shipped.",
        {"type": "starts_with", "value": "Dear customer"},
    ),
    (
        "starts_with-fail",
        "Value appears later, not at the start",
        [],
        "Hello. Dear customer, your order shipped.",
        {"type": "starts_with", "value": "Dear customer"},
    ),
    (
        "ends_with-pass",
        "Response closes with the value",
        [],
        "Thanks for reading. Not financial advice.",
        {"type": "ends_with", "value": "Not financial advice."},
    ),
    (
        "ends_with-fail",
        "Trailing newline defeats ends_with",
        ["whitespace"],
        "Thanks for reading. Not financial advice.\n",
        {"type": "ends_with", "value": "Not financial advice."},
    ),
    (
        "contains_any-pass",
        "At least one alternative present",
        [],
        "Please contact support for a refund.",
        {"type": "contains_any", "value": ["refund", "chargeback", "reversal"]},
    ),
    (
        "contains_any-fail",
        "No alternative present",
        [],
        "Please contact support.",
        {"type": "contains_any", "value": ["refund", "chargeback", "reversal"]},
    ),
    (
        "contains_all-pass",
        "Every required phrase present",
        [],
        "Risk warning: past performance is not indicative of future results.",
        {"type": "contains_all", "value": ["Risk warning", "past performance"]},
    ),
    (
        "contains_all-fail",
        "One required phrase missing",
        [],
        "Past performance is not indicative of future results.",
        {"type": "contains_all", "value": ["Risk warning", "past performance"]},
    ),
    (
        "contains_all-casefold",
        "Case folding applies to every item in the list",
        ["casefold"],
        "RISK WARNING: PAST PERFORMANCE IS NOT INDICATIVE.",
        {
            "type": "contains_all",
            "value": ["Risk warning", "past performance"],
            "case_sensitive": False,
        },
    ),
    (
        "regex-pass",
        "Anchored pattern matches the whole response",
        ["regex"],
        "Order 10432 shipped",
        {"type": "regex", "value": r"^Order \d+ shipped$"},
    ),
    (
        "regex-search-not-fullmatch",
        "regex searches anywhere; it does not require a full match",
        ["regex"],
        "Note: Order 10432 shipped today.",
        {"type": "regex", "value": r"Order \d+ shipped"},
    ),
    (
        "regex-fail",
        "Pattern absent",
        ["regex"],
        "Order pending",
        {"type": "regex", "value": r"Order \d+ shipped"},
    ),
    (
        "regex-matches-raw-response",
        "regex runs against the raw response, so casefold's ß→ss never happens; "
        "compare with contains-casefold-sharp-s, which passes on the same input",
        ["regex", "raw_response"],
        "Die Straße ist gesperrt.",
        {"type": "regex", "value": "strasse", "case_sensitive": False},
    ),
    (
        "regex-ignorecase",
        "case_sensitive=false becomes re.IGNORECASE, not a normalized comparison",
        ["regex", "raw_response"],
        "REFUND issued",
        {"type": "regex", "value": "refund", "case_sensitive": False},
    ),
    (
        "regex-python-inline-flag",
        "Python re accepts an inline (?i) flag that most other dialects reject",
        ["regex", "python_re_only"],
        "REFUND issued",
        {"type": "regex", "value": "(?i)refund"},
    ),
    (
        "min_length-pass",
        "Response is long enough",
        [],
        "A sufficiently detailed answer.",
        {"type": "min_length", "value": 10},
    ),
    (
        "min_length-fail",
        "Response is too short",
        [],
        "Too short.",
        {"type": "min_length", "value": 50},
    ),
    (
        "min_length-boundary",
        "Bound is inclusive",
        [],
        "0123456789",
        {"type": "min_length", "value": 10},
    ),
    (
        "min_length-code-points",
        "Three astral emoji are 3 code points, not the 6 UTF-16 units JS reports",
        ["code_points"],
        "\U0001f44d\U0001f44d\U0001f44d",
        {"type": "min_length", "value": 4},
    ),
    (
        "max_length-pass",
        "Response is short enough",
        [],
        "Brief.",
        {"type": "max_length", "value": 20},
    ),
    (
        "max_length-fail",
        "Response is too long",
        [],
        "This response runs well past the configured maximum length.",
        {"type": "max_length", "value": 20},
    ),
    (
        "max_length-code-points",
        "Three astral emoji fit a max_length of 3",
        ["code_points"],
        "\U0001f44d\U0001f44d\U0001f44d",
        {"type": "max_length", "value": 3},
    ),
    (
        "max_length-zwj-sequence",
        "A ZWJ family emoji is 5 code points: three emoji joined by two ZWJs",
        ["code_points"],
        "\U0001f468‍\U0001f469‍\U0001f467",
        {"type": "max_length", "value": 5},
    ),
]


def build_payload() -> Dict[str, Any]:
    cases: List[Dict[str, Any]] = []
    seen: set[str] = set()
    for case_id, description, tags, response, assertion_payload in CASES:
        if case_id in seen:
            raise ValueError(f"Duplicate conformance case id: {case_id}")
        seen.add(case_id)
        assertion = AssertionConfig.model_validate(
            {"name": case_id, **assertion_payload}
        )
        (result,) = evaluate_assertions(response, [assertion])
        cases.append(
            {
                "id": case_id,
                "description": description,
                "tags": tags,
                "response": response,
                "assertion": assertion.model_dump(mode="json"),
                "passed": result.passed,
            }
        )
    return {
        "schema_version": SCHEMA_VERSION,
        "generated_by": "scripts/export_assertion_conformance.py",
        "notes": NOTES,
        "cases": cases,
    }


def main() -> None:
    payload = build_payload()
    OUTPUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n")
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(payload['cases'])} cases)")


if __name__ == "__main__":
    main()
